version: "3.3"

services:

  mysql:
    image: mysql:5.7
    restart: always
    env_file:
      - ./mysql-container.env
    volumes:
      - mysql_data:/var/lib/mysql
    
  pythonapp:
    build: .
    command: sh -c "sleep 5s; flask run --host=0.0.0.0 --reload" 
    ports:
      - 5000:5000
    depends_on:
      - mysql
    env_file:
      - ./.env
    volumes:
      - ./:/app
    working_dir: /app

volumes: 
  mysql_data: